/**
 * Backup format v2 — the shared contract for export, validation, planning and import (backup spec §5).
 * Pure: no react-native or expo import, so every backup module is unit-tested in Jest.
 */

export const BACKUP_FORMAT = "aj-backup";
export const BACKUP_VERSION = 2;
export const MANIFEST_FILE = "manifest.json";

/** Data files inside the zip, keyed by table. */
export const DATA_FILES = {
  customers: "data/customers.json",
  rehan: "data/rehan.json",
  rehanTransactions: "data/rehan_transactions.json",
  lenden: "data/lenden.json",
  lendenItems: "data/lenden_items.json",
  oldJewellery: "data/lenden_old_jewellery_items.json",
  jamaEntries: "data/jama_entries.json",
} as const;

export type TableKey = keyof typeof DATA_FILES;

/** Parents before children: the order rows are validated, planned and inserted in. */
export const TABLE_KEYS: TableKey[] = [
  "customers",
  "rehan",
  "rehanTransactions",
  "lenden",
  "lendenItems",
  "oldJewellery",
  "jamaEntries",
];

/** Lower-case UUID v4, as generated by SQLite (see UUID_SQL in the database layer). */
export const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;

// ---------- Rows as stored in a v2 backup (relationships by UUID) ----------

export interface CustomerRow {
  uuid: string;
  name: string;
  address: string | null;
  mobileNumber: string | null;
  nickname: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface RehanRow {
  uuid: string;
  /** null = the customer was not on file when exported. */
  customerUuid: string | null;
  productName: string | null;
  /** Item category (spec section 11); null for records saved before categories existed. */
  category: string | null;
  /** Running balance as stored (principal ± diya/jama). */
  amount: number | null;
  /** null is accepted: a few old rows have no status. */
  status: number | null;
  openDate: string;
  closedDate: string | null;
  /** Relative paths inside the zip: media/<uuid>/<n>-<name>. */
  media: string[];
  updatedAt: string;
}

export interface RehanTransactionRow {
  uuid: string;
  rehanUuid: string;
  type: "diya" | "jama";
  amount: number;
  date: string;
  updatedAt: string;
}

export interface LendenRow {
  uuid: string;
  customerUuid: string | null;
  date: string;
  amount: number | null;
  discount: number | null;
  remaining: number | null;
  jama: number | null;
  baki: number | null;
  status: number | null;
  billNo: number | null;
  amountOverridden: number | null;
  media: string[];
  updatedAt: string;
}

export interface LendenItemRow {
  uuid: string;
  lendenUuid: string;
  position: number;
  name: string;
  /** Item category (spec section 11); null for items saved before categories existed. */
  category: string | null;
  metal: string | null;
  purity: string | null;
  weight: number | null;
  qty: number | null;
  rate: number | null;
  total: number;
  updatedAt: string;
}

export interface OldJewelleryRow {
  uuid: string;
  lendenUuid: string;
  position: number;
  description: string;
  metal: string | null;
  purity: string | null;
  weight: number | null;
  value: number;
  updatedAt: string;
}

export interface JamaEntryRow {
  uuid: string;
  lendenUuid: string;
  amount: number;
  date: string;
  updatedAt: string;
}

export interface BackupData {
  customers: CustomerRow[];
  rehan: RehanRow[];
  rehanTransactions: RehanTransactionRow[];
  lenden: LendenRow[];
  lendenItems: LendenItemRow[];
  oldJewellery: OldJewelleryRow[];
  jamaEntries: JamaEntryRow[];
}

export interface ManifestFileEntry {
  count: number;
  /** fnv1a over the exact JSON text of the file, 8 lower-case hex digits. */
  checksum: string;
}

export interface Manifest {
  format: typeof BACKUP_FORMAT;
  version: typeof BACKUP_VERSION;
  createdAt: string;
  files: Record<string, ManifestFileEntry>;
  media: { count: number; missing: number };
  warnings: string[];
}

// ---------- Local rows as read from SQLite (numeric ids, absolute media paths) ----------

export type LocalCustomer = CustomerRow & { id: number };
export type LocalRehan = Omit<RehanRow, "customerUuid" | "media"> & { id: number; userId: number; media: string[] };
export type LocalRehanTransaction = Omit<RehanTransactionRow, "rehanUuid"> & { id: number; rehanId: number };
export type LocalLenden = Omit<LendenRow, "customerUuid" | "media"> & { id: number; userId: number; media: string[] };
export type LocalLendenItem = Omit<LendenItemRow, "lendenUuid"> & { id: number; lendenId: number };
export type LocalOldJewellery = Omit<OldJewelleryRow, "lendenUuid"> & { id: number; lendenId: number };
export type LocalJamaEntry = Omit<JamaEntryRow, "lendenUuid"> & { id: number; lendenId: number };

/** A consistent read of the whole ledger (one read transaction). Media are absolute file paths. */
export interface LocalSnapshot {
  customers: LocalCustomer[];
  rehan: LocalRehan[];
  rehanTransactions: LocalRehanTransaction[];
  lenden: LocalLenden[];
  lendenItems: LocalLendenItem[];
  oldJewellery: LocalOldJewellery[];
  jamaEntries: LocalJamaEntry[];
}

// ---------- Planning and import results ----------

export interface TableSummary {
  total: number;
  insert: number;
  same: number;
  conflict: number;
}

export interface MergePlan {
  summary: Record<TableKey, TableSummary>;
  /** Rows to insert, parents before children. */
  insert: BackupData;
  /** Rehan transactions inserted under a rehan already on the phone: apply to its balance (diya +, jama −). */
  applyToBalance: string[];
  /** Len-den already on the phone that received new jama entries: recalculate jama/baki. */
  recomputeLenden: string[];
  conflicts: { table: TableKey; uuid: string }[];
  /** Bill numbers in the backup used by a different bill on the phone. */
  billNoClashes: number[];
}

export type ImportMode = "merge" | "replace";

export interface ImportPreview {
  kind: "v2" | "legacy";
  createdAt: string | null;
  counts: Record<TableKey, number>;
  /** Null for legacy backups (merge not allowed). */
  merge: Record<TableKey, TableSummary> | null;
  billNoClashes: number[];
  missingMedia: number;
  warnings: string[];
}

export interface ImportResult {
  mode: ImportMode;
  inserted: number;
  skipped: number;
  conflicts: number;
  photos: number;
}

/** A user-facing failure: the message is shown as-is in an error banner. */
export class BackupError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "BackupError";
  }
}

export const emptySummary = (): Record<TableKey, TableSummary> =>
  Object.fromEntries(TABLE_KEYS.map((k) => [k, { total: 0, insert: 0, same: 0, conflict: 0 }])) as Record<
    TableKey,
    TableSummary
  >;
