import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F8F9FA" },
  loader: { flex: 1, justifyContent: "center", alignItems: "center" },
  controls: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#E0E0E0",
    gap: 8,
  },
  topControlsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  controlRow: {
    flexShrink: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  controlLabel: {
    flexShrink: 1,
    fontSize: 14,
    fontWeight: "600",
    color: "#666",
  },
  nestedControlRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    paddingLeft: 12,
    paddingRight: 10,
    paddingVertical: 6,
    borderLeftWidth: 3,
    borderLeftColor: "#007AFF",
    backgroundColor: "#F0F7FF",
    borderRadius: 8,
    marginTop: 4,
  },
  nestedLabelContainer: {
    flexShrink: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  nestedControlLabel: {
    flexShrink: 1,
    fontSize: 14,
    fontWeight: "600",
    color: "#007AFF",
  },
  billNoInput: {
    minWidth: 70,
    backgroundColor: "#F0F7FF",
    borderWidth: 1,
    borderColor: "#D0E4FF",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontSize: 15,
    fontWeight: "700",
    color: "#1A1A1A",
  },
  paperRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  segment: {
    flexDirection: "row",
    borderWidth: 1,
    borderColor: "#D0E4FF",
    borderRadius: 8,
    overflow: "hidden",
  },
  segmentOption: {
    paddingHorizontal: 18,
    paddingVertical: 6,
    backgroundColor: "#F0F7FF",
  },
  segmentOptionActive: { backgroundColor: "#007AFF" },
  segmentText: { fontSize: 14, fontWeight: "700", color: "#007AFF" },
  segmentTextActive: { color: "#fff" },
  paperHint: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: "#FFF8E1",
  },
  paperHintText: { flex: 1, fontSize: 12, color: "#B26A00" },
  preview: { flex: 1 },
  webview: { flex: 1, backgroundColor: "#EDEDED" },
  updating: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.6)",
  },
  actions: {
    flexDirection: "row",
    gap: 12,
    padding: 16,
    backgroundColor: "#fff",
    borderTopWidth: 1,
    borderTopColor: "#E0E0E0",
  },
  action: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 15,
    borderRadius: 14,
  },
  shareAction: { backgroundColor: "#25A244" },
  printAction: { backgroundColor: "#B8860B" },
  actionDisabled: { opacity: 0.5 },
  actionText: { color: "#fff", fontSize: 16, fontWeight: "700" },
});
